version: '3.4'

services:
  jogosonline.api:
    image: jogosonlineapi
    build:
      context: .
      dockerfile: JogosOnline.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=JogosOnlineDb;User Id=sa;Password=Ivanete1234;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ivanete1234
      - MSSQL_PID=Express
    volumes:
      - dados_sql:/var/opt/mssql

volumes:
  dados_sql: